### ISSUE TITLE
Allow placeholders in tag name

### ISSUE THREAD

**Issue by patrick-steele-idem** [philidem/htmljs-parser#32]
```xml
<app-${foo}></app-${foo}>
<app-${foo}></>
```

Placeholders should only be allowed in concise mode since the placeholder would be ambiguous in concise mode if it was at the beginning.

**Comment by yomed** [comment]
Hey @patrick-steele-idem this is a really cool feature! Wouldn't this only be allowed in verbose mode?

**Comment by patrick-steele-idem** [comment]
Hey @yomed, I updated the description to make it correct. Placeholders can be used in tag names for both verbose and concise mode, but in concise mode the placeholder cannot be at the beginning. Also, this feature description was probably misleading in that while the parser will recognize placeholders in tag names, the Marko compiler won't know the actual tag name at compilation time so the Marko compiler will just end up producing code that renders a normal HTML tag with a dynamic tag name. For example, the Marko compiler will end up producing code similar to the following:

```javascript
function create(__helpers) {
  var str = __helpers.s,
      empty = __helpers.e,
      notEmpty = __helpers.ne,
      escapeXml = __helpers.x;

  return function render(data, out) {
    out.w("<" +
      data.myTagName +
      " class=\"my-class\" foo=\"bar\">My nested content</" +
      data.myTagName +
      ">");
  };
}

(module.exports = require("marko").c(__filename)).c(create);
```

So while this feature is cool, I suspect it is not as cool as you hoped. In hopes that you won't be too disappointed, I opened up another feature proposal: https://github.com/marko-js/marko/issues/227

Please add your comments to that new issue. Thanks!

**Comment by yomed** [comment]
That's true, I had misunderstood. Although even without compiling custom tags this is still pretty useful. I have had some use cases where I wanted to use `<div>` vs. `<span>` in different scenarios and would end up with lots of if statements in the template (when I'd prefer to store it in variables instead). Let me think about the custom imports some more.
