### ISSUE TITLE
Parser should validate opening and closing tags

### ISSUE THREAD

**Issue by patrick-steele-idem** [philidem/htmljs-parser#4]

**Comment by philidem** [comment]
@patrick-steele-idem I would recommend implement a validating parser on top of the baseline parser.

**Comment by patrick-steele-idem** [comment]
Ok, good. Already done that way :) The default parser will be validating, but there will still be an option to use the non-validating parser. The validating parser also has better handling of tags that are "open tag open" and will do some backtracking to match up tags correctly.

**Comment by patrick-steele-idem** [comment]
Also, I did inventory of all of the HTML tags to figure out which HTML tags are "open tag only" or that require a closing tag (either self-closing or not self-closing). This information ensures that tags are efficiently handled correctly when using the validating parser.
